/*
 * GUI.java
 *
 * Created on Jul 6, 2012, 2:35:48 PM
 */
package tm1servicescript;

import java.awt.Frame;

/**
 *The Main Graphical Interface for the end user
 * @author tom.saxton-howes
 */
public class GUI extends java.awt.Frame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathField = new java.awt.TextField();
        NameField = new java.awt.TextField();
        DataField = new java.awt.TextField();
        Addbutton = new java.awt.Button();
        PathLabel = new java.awt.Label();
        Namelabel = new java.awt.Label();
        dataLabel = new java.awt.Label();
        Removebutton = new java.awt.Button();
        Helpbutton = new java.awt.Button();

        setBackground(new java.awt.Color(255, 205, 156));
        setTitle("TM1 Windows Service Creator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pathField.setText("C:\\Program Files\\cognos\\tm1\\bin\\");

            Addbutton.setLabel("Add");
            Addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    AddbuttonMouseClicked(evt);
                }
            });

            PathLabel.setName(""); // NOI18N
            PathLabel.setText("TM1 install path");

            Namelabel.setText("name of server");

            dataLabel.setText("Data Directory");

            Removebutton.setLabel("remove");
            Removebutton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    RemovebuttonMouseClicked(evt);
                }
            });

            Helpbutton.setActionCommand("Helpbutton");
            Helpbutton.setLabel("Help");
            Helpbutton.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    HelpbuttonMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Addbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DataField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pathField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(Removebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Helpbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pathField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PathLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DataField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Removebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Helpbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            PathLabel.getAccessibleContext().setAccessibleName("PathLabel");
            PathLabel.getAccessibleContext().setAccessibleDescription("");
            Helpbutton.getAccessibleContext().setAccessibleName("Helpbutton");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void AddbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbuttonMouseClicked
        TM1ServiceScript.installServer(getTM1Loc(), getTM1Data(), getTM1ServerName());
    }//GEN-LAST:event_AddbuttonMouseClicked

    private void RemovebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemovebuttonMouseClicked
        TM1ServiceScript.removeServer(getTM1Loc(), getTM1ServerName());
    }//GEN-LAST:event_RemovebuttonMouseClicked

    private void HelpbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpbuttonMouseClicked
        Help helpmsg = new Help(this,true);
        helpmsg.setVisible(true);
        helpmsg.dispose();
    }//GEN-LAST:event_HelpbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    /**
     * gets the TM1 location from the Location text field
     * @return TM1 location
     */
    public String getTM1Loc(){
        String TM1Loc;
        TM1Loc = pathField.getText().toLowerCase();
        if(TM1Loc.endsWith("\\")){
            TM1Loc = TM1Loc.replaceAll("program files", "progra~1");
            TM1Loc = TM1Loc.replaceAll("program files (x86)", "progra~2");
            return TM1Loc;
        }else{
            MsgBox msgbox = new MsgBox(this,"TM1 Location must end with a \\");
            msgbox.dispose();
            return null;
        }
    }
    
    /**
     * gets the TM1 data file from Data text Field
     * @return TM1 data directory of the TM1 server service
     */
    public String getTM1Data(){
        String TM1Data;
        TM1Data = DataField.getText();
        if(TM1Data.endsWith("\\")){
            return TM1Data;
        }else{
            MsgBox msgbox = new MsgBox(this,"TM1 Data must end with a \\");
            msgbox.dispose();
            return null;
        }
    }
    
    /**
     * gets the TM1 server service name from the name text field
     * @return TM1 Server Service Name
     */
    public String getTM1ServerName(){
        String ServerName;
        ServerName = NameField.getText();
        return ServerName;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Addbutton;
    private java.awt.TextField DataField;
    private java.awt.Button Helpbutton;
    private java.awt.TextField NameField;
    private java.awt.Label Namelabel;
    private java.awt.Label PathLabel;
    private java.awt.Button Removebutton;
    private java.awt.Label dataLabel;
    private java.awt.TextField pathField;
    // End of variables declaration//GEN-END:variables
}
