/*
 * Help.java
 *
 * Created on May 28, 2012, 9:58:06 AM
 */
package tm1servicescript;

/**
 * A help dialog box with instructions on how to fill the form in
 * @author tom.saxton-howes
 */
public class Help extends java.awt.Dialog {

    /** Creates new form Help */
    public Help(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        OkButton = new java.awt.Button();

        setName(""); // NOI18N
        setTitle("TM1 Windows Service Creator Help");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        textArea1.setEditable(false);
        textArea1.setText("To add a Server enter the path to the TM1 bin folder, The name of the new\ntm1 server service e.g. planning sample, and the path to the data directory\ncontaining tm1.cfg then click add\n\nto remove a tm1 server enter the path to the tm1 bin folder and the name \nof the tm1 server service you wish to remove\n\nHave a problem contact the Budgeting Solutions Support desk\nsupport@budgetingsolutions.co.uk");
        add(textArea1, java.awt.BorderLayout.CENTER);

        OkButton.setLabel("OK");
        OkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkButtonMouseClicked(evt);
            }
        });
        OkButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OkButtonKeyPressed(evt);
            }
        });
        add(OkButton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void OkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkButtonMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_OkButtonMouseClicked

    private void OkButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OkButtonKeyPressed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_OkButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Help dialog = new Help(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button OkButton;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
